### PR TITLE
More autosafari improvements

### PR DESCRIPTION
**Pull request by umbralOptimatum**
- Now seeks visible shiny spawns
- Caches priority spawn data to improve performance
- Fixes softlock from starting new safari too fast
- Fixes accumulating extra safari ball animations
- Fixes potential issue when changing safari regions with an active session
- Code polish

### CODE REVIEW

**Comment by Kanzen01** [comment]
Nice one as always! Thank you, I learn a lot thanks to you. ✌️ 
To be honest you should really change the credit part for the script. You trully deserves it. 🥇 And I'm a bit ashamed having my name on it.

I wait a bit for you to commit the changes on the credit part and I will merge this onto the other repo.
Then I think it will be mergeable to the main branch.

**Comment by umbralOptimatum** [comment]
No thank you, I appreciate the sentiment but your version of the script was crucial to getting here! I'm much worse at working from scratch; I'd started a safari zone script weeks before your PR and gotten absolutely nowhere with it. Just had a walk speed increase working, nothing as fancy or imaginative as automatically navigating and battling. Having your fully-working script is what allowed me to focus on improving individual features and gave me inspiration for new ones. 😁

**Comment by umbralOptimatum** [comment]
And yeah, should be ready to merge into the main project!

**Comment by Kanzen01** [comment]
Well, so let's stay like this. But I trully meant what I said. You are awesome!

I now merge to the main branch and we can wait for the final merge. :D

**Comment by umbralOptimatum** [comment]
Oops, just noticed a readme formatting issue snuck through. I moved the script's link in the top section to be in alphabetical order like the rest, but forgot to redo the numbering. And looks like git left a second link with older formatting at the end of the list? Should be a quick fix.

**Pull request merged**
